import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="keywords"
          content="nextjs , huntingcoder blog , hunting coder "
        />
        <link rel="icon" href="/coder.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.center}>
          <h1>Hunting Coder</h1>
          <p>Welcome Coders for Hunting the code</p>
        </div>

        <div className={styles.content}>
          <h2>Latest Blog:</h2>
          <div className={styles.deatil}>
            <h3>Learn React JS </h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi,
              ipsa!
            </p>
          </div>
          <div className={styles.deatil}>
            <h3>Learn React JS </h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi,
              ipsa!
            </p>
          </div>
          <div className={styles.deatil}>
            <h3>Learn React JS </h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi,
              ipsa!
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
